#!/usr/bin/env python3
"""Data generator for the performance study (section 8.1).

Writes R(a, b) and S(b, c) as relation definition files:

    python gen_data.py --n 1000 --m 1000 --match 1 --out data/generated

--n      tuples in R
--m      tuples in S
--match  the match rate k: how many S tuples each R tuple joins with on
         R.b = S.b, on average. It can be fractional, e.g. 0.1 means
         "1 in 10 R tuples has a partner".

How the match rate is produced
------------------------------
Let K = round(m / k) be the size of the key space (at least 1).

* S.b of the i-th S tuple is  i mod K.
* R.b is drawn uniformly at random from 0 .. K-1.

When K <= m, every key occurs m/K = k times in S, so every R tuple finds
about k partners. When K > m (k < 1), only keys 0 .. m-1 exist in S, so an
R tuple finds a partner with probability m/K = k. Either way, the expected
join size is n * k. With k = 1, K = m, and every R tuple matches exactly once,
so the join returns exactly n tuples.

a and c are 0..n-1 and 0..m-1, so every generated tuple is distinct.
"""
from __future__ import annotations

import argparse
import os
import random


def generate(n: int, m: int, match: float, seed: int = 42):
    if n < 0 or m < 0:
        raise ValueError("n and m must be non-negative")
    if match <= 0:
        raise ValueError("--match must be positive")
    rng = random.Random(seed)
    K = max(1, round(m / match))
    r_rows = [(i, rng.randrange(K)) for i in range(n)]
    s_rows = [(i % K, i) for i in range(m)]
    return r_rows, s_rows


def write_relation(path: str, name: str, attrs, rows) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"// generated by gen_data.py: {len(rows)} tuples\n")
        f.write(f"{name} ({', '.join(attrs)}) = {{\n")
        for row in rows:
            f.write("  " + ", ".join(str(v) for v in row) + "\n")
        f.write("}\n")


def write_files(n: int, m: int, match: float, out_dir: str, seed: int = 42):
    """Write R and S into out_dir. Return the two file paths."""
    os.makedirs(out_dir, exist_ok=True)
    r_rows, s_rows = generate(n, m, match, seed)
    tag = f"n{n}_m{m}_k{match:g}"
    r_path = os.path.join(out_dir, f"R_{tag}.ra")
    s_path = os.path.join(out_dir, f"S_{tag}.ra")
    write_relation(r_path, "R", ["a", "b"], r_rows)
    write_relation(s_path, "S", ["b", "c"], s_rows)
    return r_path, s_path


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate R(a,b) and S(b,c)")
    ap.add_argument("--n", type=int, required=True, help="tuples in R")
    ap.add_argument("--m", type=int, required=True, help="tuples in S")
    ap.add_argument("--match", type=float, default=1.0,
                    help="average number of S tuples each R tuple joins with")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out", default="data/generated")
    args = ap.parse_args()
    try:
        r_path, s_path = write_files(args.n, args.m, args.match, args.out, args.seed)
    except (ValueError, OSError) as e:
        print(f"Error: {e}")
        raise SystemExit(1)
    print(f"wrote {r_path} and {s_path}")


if __name__ == "__main__":
    main()
